export class CyberLawCollector {
  async collectGlobalCyberLaws(): Promise<any[]> {
    const cyberLaws = [
      {
        country: "India",
        title: "Information Technology Act, 2000 (Amended 2008)",
        description: "Primary legislation governing cyber crimes and electronic commerce in India",
        sections: [
          {
            section: "66",
            title: "Computer Related Offences",
            description: "Punishment for computer related offences including hacking",
            applicable_offenses: ["Hacking", "Data Theft", "System Damage"],
            examples: ["Unauthorized access to computer systems", "Data destruction", "Virus attacks"],
          },
          {
            section: "66B",
            title: "Identity Theft",
            description: "Punishment for dishonestly receiving stolen computer resource",
            applicable_offenses: ["Identity Theft", "Impersonation"],
            examples: ["Using someone else's digital identity", "Fraudulent use of electronic signatures"],
          },
          {
            section: "66C",
            title: "Identity Theft",
            description: "Punishment for identity theft",
            applicable_offenses: ["Identity Theft", "Impersonation"],
            examples: ["Using someone's password dishonestly", "Fraudulent use of electronic signatures"],
          },
          {
            section: "66D",
            title: "Cheating by Personation",
            description: "Punishment for cheating by personation using computer resource",
            applicable_offenses: ["Online Fraud", "Impersonation"],
            examples: ["Cheating by impersonation using computer", "Fraudulent online transactions"],
          },
        ],
        penalties: [
          {
            offense: "Hacking (Section 66)",
            min_penalty: "₹1,00,000",
            max_penalty: "₹5,00,000",
            imprisonment: "Up to 3 years",
            fine: "Up to ₹5,00,000",
          },
          {
            offense: "Identity Theft (Section 66C)",
            min_penalty: "₹1,00,000",
            max_penalty: "₹1,00,000",
            imprisonment: "Up to 3 years",
            fine: "Up to ₹1,00,000",
          },
        ],
        last_updated: "2008-10-27",
        jurisdiction: "All of India",
      },
      {
        country: "United States",
        title: "Computer Fraud and Abuse Act (CFAA)",
        description: "Federal law that criminalizes computer-related offenses",
        sections: [
          {
            section: "1030(a)(1)",
            title: "Classified Information",
            description: "Accessing classified information without authorization",
            applicable_offenses: ["Unauthorized Access", "Espionage"],
            examples: ["Accessing classified government data", "Military information theft"],
          },
          {
            section: "1030(a)(2)",
            title: "Financial Information",
            description: "Accessing financial records or credit information",
            applicable_offenses: ["Financial Fraud", "Identity Theft"],
            examples: ["Bank account hacking", "Credit card information theft"],
          },
          {
            section: "1030(a)(4)",
            title: "Fraud and Related Activity",
            description: "Using computers to commit fraud",
            applicable_offenses: ["Computer Fraud", "Wire Fraud"],
            examples: ["Online banking fraud", "E-commerce scams"],
          },
        ],
        penalties: [
          {
            offense: "First-time offender (1030(a)(2))",
            min_penalty: "$0",
            max_penalty: "$250,000",
            imprisonment: "Up to 1 year",
            fine: "Up to $250,000",
          },
          {
            offense: "Repeat offender",
            min_penalty: "$0",
            max_penalty: "$250,000",
            imprisonment: "Up to 10 years",
            fine: "Up to $250,000",
          },
        ],
        last_updated: "2008-05-07",
        jurisdiction: "Federal - All US States",
      },
      {
        country: "United Kingdom",
        title: "Computer Misuse Act 1990",
        description: "Primary legislation covering computer crimes in the UK",
        sections: [
          {
            section: "1",
            title: "Unauthorized Access",
            description: "Unauthorized access to computer material",
            applicable_offenses: ["Hacking", "Unauthorized Access"],
            examples: ["Password cracking", "System intrusion"],
          },
          {
            section: "2",
            title: "Unauthorized Access with Intent",
            description: "Unauthorized access with intent to commit further offences",
            applicable_offenses: ["Advanced Hacking", "Cyber Espionage"],
            examples: ["Hacking to commit fraud", "Corporate espionage"],
          },
          {
            section: "3",
            title: "Unauthorized Modification",
            description: "Unauthorized acts causing modification of computer material",
            applicable_offenses: ["Data Destruction", "Malware", "DDoS"],
            examples: ["Virus creation", "Website defacement", "DDoS attacks"],
          },
        ],
        penalties: [
          {
            offense: "Section 1 - Basic unauthorized access",
            min_penalty: "£0",
            max_penalty: "£5,000",
            imprisonment: "Up to 6 months",
            fine: "Up to £5,000",
          },
          {
            offense: "Section 3 - Unauthorized modification",
            min_penalty: "£0",
            max_penalty: "Unlimited",
            imprisonment: "Up to 10 years",
            fine: "Unlimited",
          },
        ],
        last_updated: "2015-05-03",
        jurisdiction: "England, Wales, Scotland, Northern Ireland",
      },
      {
        country: "Australia",
        title: "Cybercrime Act 2001",
        description: "Federal legislation addressing cybercrime in Australia",
        sections: [
          {
            section: "477.1",
            title: "Unauthorized Access",
            description: "Unauthorized access to, or modification of, restricted data",
            applicable_offenses: ["Hacking", "Data Breach"],
            examples: ["Accessing protected systems", "Modifying restricted data"],
          },
          {
            section: "477.2",
            title: "Unauthorized Modification",
            description: "Unauthorized modification of data to cause damage",
            applicable_offenses: ["Data Destruction", "System Sabotage"],
            examples: ["Deleting critical data", "System corruption"],
          },
          {
            section: "477.3",
            title: "Unauthorized Impairment",
            description: "Unauthorized impairment of electronic communication",
            applicable_offenses: ["DDoS", "Network Disruption"],
            examples: ["DDoS attacks", "Network jamming"],
          },
        ],
        penalties: [
          {
            offense: "Unauthorized access (477.1)",
            min_penalty: "AUD $0",
            max_penalty: "AUD $133,200",
            imprisonment: "Up to 2 years",
            fine: "Up to AUD $133,200",
          },
          {
            offense: "Serious computer offence",
            min_penalty: "AUD $0",
            max_penalty: "AUD $666,000",
            imprisonment: "Up to 10 years",
            fine: "Up to AUD $666,000",
          },
        ],
        last_updated: "2021-12-02",
        jurisdiction: "Commonwealth of Australia",
      },
      {
        country: "Japan",
        title: "Unauthorized Computer Access Law",
        description: "Law prohibiting unauthorized computer access in Japan",
        sections: [
          {
            section: "3",
            title: "Prohibited Acts",
            description: "Prohibition of unauthorized computer access",
            applicable_offenses: ["Unauthorized Access", "Hacking"],
            examples: ["Password cracking", "System intrusion"],
          },
          {
            section: "4",
            title: "Facilitating Unauthorized Access",
            description: "Prohibition of acts facilitating unauthorized access",
            applicable_offenses: ["Providing Hacking Tools", "Password Sharing"],
            examples: ["Sharing passwords", "Distributing hacking software"],
          },
        ],
        penalties: [
          {
            offense: "Unauthorized access",
            min_penalty: "¥0",
            max_penalty: "¥1,000,000",
            imprisonment: "Up to 1 year",
            fine: "Up to ¥1,000,000",
          },
          {
            offense: "Facilitating unauthorized access",
            min_penalty: "¥0",
            max_penalty: "¥500,000",
            imprisonment: "Up to 1 year",
            fine: "Up to ¥500,000",
          },
        ],
        last_updated: "2012-05-01",
        jurisdiction: "Japan",
      },
      {
        country: "China",
        title: "Cybersecurity Law of the People's Republic of China",
        description: "Comprehensive cybersecurity legislation in China",
        sections: [
          {
            section: "27",
            title: "Network Security Incidents",
            description: "Requirements for handling network security incidents",
            applicable_offenses: ["Data Breach", "System Compromise"],
            examples: ["Personal data leaks", "Critical infrastructure attacks"],
          },
          {
            section: "44",
            title: "Personal Information Protection",
            description: "Protection of personal information collected by network operators",
            applicable_offenses: ["Privacy Violation", "Data Misuse"],
            examples: ["Unauthorized data collection", "Personal information trading"],
          },
        ],
        penalties: [
          {
            offense: "Violation of personal information protection",
            min_penalty: "¥100,000",
            max_penalty: "¥1,000,000",
            imprisonment: "Administrative penalty",
            fine: "¥100,000 to ¥1,000,000",
          },
          {
            offense: "Critical information infrastructure violation",
            min_penalty: "¥100,000",
            max_penalty: "¥1,000,000",
            imprisonment: "Business suspension possible",
            fine: "¥100,000 to ¥1,000,000",
          },
        ],
        last_updated: "2017-06-01",
        jurisdiction: "People's Republic of China",
      },
      {
        country: "South Africa",
        title: "Cybercrimes Act, 2020",
        description: "Comprehensive cybercrime legislation for South Africa",
        sections: [
          {
            section: "2",
            title: "Unlawful Access",
            description: "Unlawful access to a computer system or data",
            applicable_offenses: ["Hacking", "Unauthorized Access"],
            examples: ["System intrusion", "Data access without permission"],
          },
          {
            section: "5",
            title: "Cyber Fraud",
            description: "Unlawful acts in respect of software or hardware tool",
            applicable_offenses: ["Cyber Fraud", "Online Scams"],
            examples: ["Online banking fraud", "E-commerce scams"],
          },
          {
            section: "16",
            title: "Cyber Bullying",
            description: "Disclosure of data message to cause harm",
            applicable_offenses: ["Cyberbullying", "Online Harassment"],
            examples: ["Revenge porn", "Online stalking"],
          },
        ],
        penalties: [
          {
            offense: "Unlawful access",
            min_penalty: "R0",
            max_penalty: "R50,000,000",
            imprisonment: "Up to 15 years",
            fine: "Up to R50,000,000",
          },
          {
            offense: "Cyber bullying",
            min_penalty: "R0",
            max_penalty: "R150,000",
            imprisonment: "Up to 3 years",
            fine: "Up to R150,000",
          },
        ],
        last_updated: "2020-12-01",
        jurisdiction: "Republic of South Africa",
      },
    ]

    return cyberLaws
  }

  async collectIncidentData(): Promise<any[]> {
    const incidents = [
      {
        country: "India",
        incident_type: "Data Breach",
        severity: "HIGH",
        description: "Major healthcare data breach affecting 2.3 million patient records",
        affected_sectors: ["Healthcare", "Insurance"],
        reported_date: "2024-01-15",
        resolved_date: "2024-01-25",
        legal_actions: ["IT Act Section 43A violation", "DPDP Act compliance review"],
        applicable_laws: ["IT_ACT_2000", "DPDP_ACT_2023"],
        source: "CERT-IN",
      },
      {
        country: "United States",
        incident_type: "Ransomware",
        severity: "CRITICAL",
        description: "Ransomware attack on critical infrastructure - power grid systems",
        affected_sectors: ["Energy", "Utilities"],
        reported_date: "2024-01-10",
        legal_actions: ["CFAA prosecution initiated", "CISA incident response"],
        applicable_laws: ["CFAA_1986", "PATRIOT_ACT"],
        source: "CISA",
      },
      {
        country: "United Kingdom",
        incident_type: "Financial Fraud",
        severity: "HIGH",
        description: "Sophisticated phishing campaign targeting UK banking customers",
        affected_sectors: ["Financial Services", "Banking"],
        reported_date: "2024-01-12",
        resolved_date: "2024-01-20",
        legal_actions: ["Computer Misuse Act prosecution", "FCA investigation"],
        applicable_laws: ["CMA_1990", "FRAUD_ACT_2006"],
        source: "NCSC-UK",
      },
      {
        country: "Australia",
        incident_type: "Identity Theft",
        severity: "MEDIUM",
        description: "Large-scale identity theft affecting government services portal",
        affected_sectors: ["Government", "Public Services"],
        reported_date: "2024-01-08",
        legal_actions: ["Cybercrime Act charges filed", "Privacy Act investigation"],
        applicable_laws: ["CYBERCRIME_ACT_2001", "PRIVACY_ACT_1988"],
        source: "ACSC",
      },
      {
        country: "Japan",
        incident_type: "Corporate Espionage",
        severity: "HIGH",
        description: "Advanced persistent threat targeting Japanese manufacturing companies",
        affected_sectors: ["Manufacturing", "Technology"],
        reported_date: "2024-01-14",
        legal_actions: ["Unauthorized Access Law prosecution", "Trade secret violation"],
        applicable_laws: ["UNAUTHORIZED_ACCESS_LAW", "UNFAIR_COMPETITION_PREVENTION_ACT"],
        source: "NISC",
      },
      {
        country: "China",
        incident_type: "Data Breach",
        severity: "HIGH",
        description: "Personal data breach affecting e-commerce platform users",
        affected_sectors: ["E-commerce", "Retail"],
        reported_date: "2024-01-11",
        legal_actions: ["Cybersecurity Law violation", "Administrative penalties"],
        applicable_laws: ["CYBERSECURITY_LAW_2017", "PERSONAL_INFORMATION_PROTECTION_LAW"],
        source: "CAC",
      },
      {
        country: "South Africa",
        incident_type: "Cyberbullying",
        severity: "MEDIUM",
        description: "Online harassment campaign targeting public figures",
        affected_sectors: ["Media", "Entertainment"],
        reported_date: "2024-01-09",
        resolved_date: "2024-01-18",
        legal_actions: ["Cybercrimes Act prosecution", "Civil defamation case"],
        applicable_laws: ["CYBERCRIMES_ACT_2020"],
        source: "SAPS",
      },
    ]

    return incidents
  }
}
